[build]
buildCommand = "cd demo && ./gradlew clean bootJar -x check -x test"

[deploy]
startCommand = "cd demo && java $JAVA_OPTS -Dserver.port=$PORT -jar $(ls -1 build/libs/*.jar | grep -v plain | head -n 1)"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
